Deduplicate L1A1s and remove from the Opfor arsenal
Bro-Nation/Mike-Force pull request #151
Opened 2023-05-14 18:31 UTC by dijksterhuis

I've done my best to honour the original values in the arsenal config while deduplicating.

2023-05-14 19:12 UTC, dijksterhuis commented on mission/config/arsenal.hpp
> +			{"vn_l1a1_01",{-1,1,1,-1}},
This was original disabled for west, but is the most basic L1A1 weapon, so have enabled at the same level as the `vn_l1a1_01_camo`

2023-05-14 19:14 UTC, dijksterhuis reviewed
I've set all the independent values to equal west, and all the civilian/east values to be disabled.

2023-05-14 19:14 UTC, dijksterhuis commented on mission/config/arsenal.hpp
> +			{"vn_l1a1_01_mrk",{-1,-1,-1,-1}}, // unknown so disabled by @dijksterhuis
I'm guessing this is some sort of marksman reference, but changing these values doesn't seem to do anything.

2023-05-14 19:14 UTC, dijksterhuis commented on mission/config/arsenal.hpp
> +			{"vn_l1a1_02_mrk",{-1,-1,-1,-1}}, // unknown so disabled by @dijksterhuis
I'm guessing this is some sort of marksman reference, but changing these values doesn't seem to do anything.

2023-05-24 21:52 UTC, wescottj98 requested changes
Dont remove any lines from here. if you want to change a given side's access to an item change the numbers accordingly. Refer to the top of the file.

2023-05-25 01:07 UTC, dijksterhuis commented
@wescottj98 

> Dont remove any lines from here. if you want to change a given side's access to an item change the numbers accordingly. Refer to the top of the file.

I did refer to the top of the file.

The lines I removed were duplicate entries for the same assets.

Cross reference modified diff lines with the removed diff lines and you should see that I've just deduplicated the entries.

2023-05-31 21:44 UTC, wescottj98 approved these changes

2023-05-31 21:44 UTC, merged