Hotfix May 22
Bro-Nation/Mike-Force pull request #301
Opened 2024-05-22 11:41 UTC by dijksterhuis

ACAV Arsenal connected

ACAV heavy vehicles -- lowered

MPs cayuse -> slick

633rd moved the medical bird back slightly

633rd ch47 medical

ARVNR whitelisting for tanks

fix MP gate

mp slick

mp patrol vehicle

blackhorse 105s at base not behsdfkjhdsfsdfstanden

Blackhorse -- Removed Berch assets

blackhorse -- slicks too

mp_arsenal no longer safe zone

spread out acav vehicles

anzac new billboard

arvnr -- arvn specific spawners to fix whitelisting issues

Muskets -- OH6A spawn fixed

7thCav -- OH6A spawn fixed

teleporters -- fixed MP missing MACV and removed berch from list of options to TP to

2024-05-22 13:47 UTC, dijksterhuis commented
testing

- ✅ ACAV Arsenal connected
- ✅ ACAV heavy vehicles -- lowered
- ✅ MPs cayuse -> slick
- ✅ 633rd moved the medical bird back slightly
- ✅ 633rd ch47 medical
- ✅ ARVNR whitelisting for tanks
- ✅ fix MP gate
- ✅ mp slick
- ✅ mp patrol vehicle
- ✅ blackhorse 105s at base not behsdfkjhdsfsdfstanden
- ✅ Blackhorse -- Removed Berch assets
- ✅ blackhorse -- slicks too
  - they've also got access to choktaws / seahorses now?
- ❌ mp_arsenal no longer safe zone
  - i'm gonna dig into this, should be working
- ✅ spread out acav vehicles
- ✅ anzac new billboard (after PR into your PR anyway)
- ✅ arvnr -- arvn specific spawners to fix whitelisting issues (wasn't the spawn issue iirc)
- ✅ Muskets -- OH6A spawn fixed
- ✅ 7thCav -- OH6A spawn fixed
- teleporters 
  - ✅ fixed MP missing MACV
  - ✅ removed berch from list of options to TP to

2024-05-22 15:02 UTC, dijksterhuis commented
testing

✅ ACAV Arsenal connected
✅ ACAV heavy vehicles -- lowered
✅ MPs cayuse -> slick
✅ 633rd moved the medical bird back slightly
✅ 633rd ch47 medical
✅ ARVNR whitelisting for tanks
✅ fix MP gate
✅ mp slick
✅ mp patrol vehicle
✅ blackhorse 105s at base not behsdfkjhdsfsdfstanden
✅ Blackhorse -- Removed Berch assets
✅ blackhorse -- slicks too
✅  mp_arsenal no longer safe zone
✅ spread out acav vehicles
✅ anzac new billboard (after PR into your PR anyway)
✅ arvnr -- arvn specific spawners to fix whitelisting issues (wasn't the spawn issue iirc)
✅ Muskets -- OH6A spawn fixed
✅ 7thCav -- OH6A spawn fixed

teleporters
✅ fixed MP missing MACV
✅ removed berch from list of options to TP to

2024-05-23 01:31 UTC, cerebral-314 requested changes
Aside from the CBA dependency everything looks good.

2024-05-23 01:31 UTC, cerebral-314 commented on maps/cam_lao_nam/mission.sqm
> +		{
Please unload ALL mods before working on the map.
Remove this dependency please.

2024-05-23 06:08 UTC, cerebral-314 approved these changes

2024-05-23 06:08 UTC, cerebral-314 commented
LGTM

2024-05-23 10:04 UTC, dijksterhuis commented
@cerebral-314 this was an earlier version of the one @wescottj98 merged prior so gonna close this.

(I messed up the push so had to create a new PR)

2024-05-23 10:04 UTC, closed without merging