Site Artillery Pickup Change
Bro-Nation/Mike-Force pull request #412
Opened 2024-10-08 17:04 UTC by Legend8-8

Disabled Pickup on arty tubes to prevent bug where there are loaded into vehicles and made invisible.
Tested and confirmed cannot be picked up but can still be spiked.
@dijksterhuis

2024-10-08 17:30 UTC, dijksterhuis commented
@Legend8-8 needs to be for all sites

2024-10-08 17:31 UTC, dijksterhuis commented
ZPUs will be affected by this, and possibly static weapons too.

2024-10-08 17:41 UTC, Legend8-8 commented
Was going to question this but figured the arty was the only asset that would be taken from sites > @Legend8-8 needs to be for all sites

2024-10-09 09:28 UTC, Legend8-8 commented
@dijksterhuis Have added AA sites, following this 

- [ ] Player gets killed within the site radius -- object is still hidden and attached to player's body

Only changed sites where the  asset itself is relevant to site completion

2024-10-17 19:02 UTC, cerebral-314 requested changes

2024-10-17 19:02 UTC, cerebral-314 commented on mission/functions/systems/sites/create/site/fn_sites_create_site_aa.sqf
> +       {
```suggestion
		{     
			_x setVariable ["vn_log_enablePickup", false];
		} forEach _objects;
```

2024-10-17 19:02 UTC, cerebral-314 commented on mission/functions/systems/sites/create/site/fn_sites_create_site_aa.sqf
> +       {
Please fix your whitespacing
Tab generally does it for you... if you need help with setting up your coding environment please feel free to DM me

2024-10-17 19:02 UTC, cerebral-314 commented on mission/functions/systems/sites/create/site/fn_sites_create_site_artillery.sqf
> +		    _x setVariable ["vn_log_enablePickup", false];
```suggestion
		_x setVariable ["vn_log_enablePickup", false];
```

2024-10-17 19:02 UTC, cerebral-314 commented on mission/functions/systems/sites/create/site/fn_sites_create_site_artillery.sqf
> +		    _x setVariable ["vn_log_enablePickup", false];
Here as well please

2024-10-17 19:27 UTC, cerebral-314 approved these changes

2024-10-17 19:27 UTC, merged